name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 🔍 Checkout Code
      uses: actions/checkout@v3

    - name: 🔧 Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🔐 Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🛠️ Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: shafi627/backend:latest .
        tags: shafi627/frontend:latest ./client

    - name: 📦 Deploy on EC2 via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.USER }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          chmod +x deploy.sh
          
          ./deploy.sh



# name: Deploy to AWS EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Backend Image
#         run: |
#           docker build -t shafi627/backend:latest .
#           docker push shafi627/backend:latest

#       - name: Build and Push Frontend Image
#         run: |
#           docker build -t shafi627/frontend:latest ./client
#           docker push shafi627/frontend:latest

#       - name: SSH into EC2 and Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.IP }}
#           username: ubuntu
#           key: ${{ secrets.PRIVATE_KEY }}
#           script: |
#             cd /home/ubuntu
#             rm -rf myapp
#             git clone https://github.com/Shafi327/Food_website_Ci-CD_Action.git myapp
#             cd myapp
#             ls -la
#             sudo docker-compose up -d

#             docker pull shafi627/backend:latest
#             docker pull shafi627/frontend:latest
#             docker-compose up -d
#             EOF
#           # script: |
#           #   cd /home/ubuntu/myapp

