name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        run: |
          docker build -t shafi627/backend:latest .
          docker push shafi627/backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t shafi627/frontend:latest ./client
          docker push shafi627/frontend:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}

          script: |
            # Remove old application directory
            rm -rf /home/ubuntu/app

            # Clone the repository
            git clone https://github.com/Shafi327/Food_website_Ci-CD_Action.git /home/ubuntu/app

            # Navigate to the correct directory
            cd /home/ubuntu/app

            # Create .env files
            echo "REACT_APP_API_URL=http://your-api-url" > client/.env
            echo "DB_USER=admin" >> .env
            echo "DB_PASS=secret" >> .env

            # Pull the latest Docker images
            sudo docker pull shafi627/backend:latest
            sudo docker pull shafi627/frontend:latest

            # Ensure docker-compose.yml exists and bring up services
            if [ -f docker-compose.yml ]; then
              sudo docker-compose up -d
            else
              echo "Error: docker-compose.yml not found in /home/ubuntu/app"
              exit 1
            fi