name: CI/CD with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and Push Backend
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      # SSH to EC2 and deploy with docker-compose
      - name: Write SSH Key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > githubaction-key.pem
          chmod 600 githubaction-key.pem

      - name: Deploy to EC2
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          ssh -i "githubaction-key.pem" \
              -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ secrets.USER }}@${{ secrets.IP }} << EOF
            cd /home/ubuntu/app
            git pull origin main
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            docker-compose pull
            docker-compose up -d
          EOF


# name: Deploy to AWS EC2

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Docker
#         uses: docker/setup-buildx-action@v2

#       - name: Log in to DockerHub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and Push Backend Image
#         run: |
#           docker build -t shafi627/backend:latest .
#           docker push shafi627/backend:latest

#       - name: Build and Push Frontend Image
#         run: |
#           docker build -t shafi627/frontend:latest ./client
#           docker push shafi627/frontend:latest

#       - name: SSH into EC2 and Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.IP }}
#           username: ubuntu
#           key: ${{ secrets.PRIVATE_KEY }}
#           script: |
#             cd /home/ubuntu
#             rm -rf myapp
#             git clone https://github.com/Shafi327/Food_website_Ci-CD_Action.git myapp
#             cd myapp
#             ls -la
#             sudo docker-compose up -d


#             docker pull shafi627/backend:latest
#             docker pull shafi627/frontend:latest
#             docker-compose up -d
#             EOF
#           # script: |
#           #   cd /home/ubuntu/myapp